spring:
  profiles:
    active: dev

logging:
  level:
    root: TRACE

feign:
  gif:
    name: gif
    url: https://api.giphy.com/v1
  currency:
    name: currency
    url: https://openexchangerates.org/api