spring:
  config:
    activate:
      on-profile: dev

name: syka

database:
  url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/alfa_bank
  username: root
  password: serega12345
  driver: com.mysql.cj.jdbc.Driver

openexchange:
  api_path: https://openexchangerates.org/api/
  app_id: 3dc88aff5fe54b5da0c7ad2da5fbc0a1
  base: USD
  symbols:
    - RUB
    - EUR
    - AED
    - AMD
  to_compare: AMD

giphy:
  api_path: https://api.giphy.com/v1/gifs/search
  api_key: Fe2hj8lNwi4E4yEg88raHpJqdjHdyWW9
  limit: 1
  rating: r
  query:
    rich: rich
    broke: broke


