spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/alfa_bank
    username: root
    password: serega12345
    driver-class: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: TRACE

feign:
  gif:
    name: gif
    url: https://api.giphy.com/v1
  currency:
    name: currency
    url: https://openexchangerates.org/api